In [1]:
import numpy as np
import SimpleITK as sitk
import pyvista as pv
import point_cloud_utils as pcu

from morphometry import hip, utils
from matplotlib import pyplot as plt

In [33]:
import importlib
importlib.reload(hip)

<module 'morphometry.hip' from '/home/simon/Work/morpohmetry/morphometry/hip.py'>

# Femoral head center

In [2]:
mask = sitk.ReadImage('/home/simon/Data/Hamburg/100016_30_PD_FS_SPC_COR FK/Segmentation_12.seg.nrrd')
spacing = mask.GetSpacing()
z_ratio = abs(spacing[2]) / 2 * abs(spacing[0])

In [3]:
mask_array = sitk.GetArrayFromImage(mask)
mask_array = np.where(mask_array == 1, 1, 0)

In [4]:
mask_array.shape

(160, 264, 384)

Axis order: z = coronal, y = axial, z = sagittal

In [5]:
mask_array = np.swapaxes(mask_array, 0, 1)

In [6]:
r, c = hip.get_femoral_head_center(mask_array, z_ratio)

(60, 106)
36.8 83.2


In [25]:
r, c

(22.336863496895106, (169, 60, 105))

In [28]:
p = pv.Plotter()
p.add_mesh(pv.PolyData(np.argwhere(mask_array)), color='b')
p.add_mesh(pv.Sphere(22, (169, 60, 105)))
p.enable_eye_dome_lighting()
p.show()

/home/simon/anaconda3/envs/shapes/lib/python3.10/site-packages/pyvista/core/utilities/points.py:55: UserWarning: Points is not a float type. This can cause issues when transforming or applying filters. Casting to ``np.float32``. Disable this by passing ``force_float=False``.
  warnings.warn(


Widget(value='<iframe src="http://localhost:44947/index.html?ui=P_0x7c29f7fb2080_6&reconnect=auto" class="pyvi…

# Femoral neck axis

In [52]:
endpoint = hip.get_femoral_neck_axis(mask_array)

In [13]:
point_cloud = np.argwhere(mask_array)
np.argmin(point_cloud[:, 2])

73246

In [15]:
idx = pcu.downsample_point_cloud_poisson_disk(point_cloud.astype('float32'), radius=0, target_num_samples=1000)

In [37]:
point_cloud[73246]

array([196,  88,  54])

In [42]:
p = pv.Plotter()
p.add_mesh(pv.PolyData(point_cloud[idx]), color='b')
p.add_lines(np.array([np.array(c), point_cloud[73246]]), color='r')
p.add_mesh(pv.Sphere(22, (169, 60, 105)))
p.show()

Widget(value='<iframe src="http://localhost:44947/index.html?ui=P_0x7c29e8bb5cf0_12&reconnect=auto" class="pyv…

# Femoral shaft axis

In [89]:
importlib.reload(hip)

<module 'morphometry.hip' from '/home/simon/Work/morpohmetry/morphometry/hip.py'>

In [90]:
p0, p1 = hip.get_femoral_shaft_axis(mask_array)

In [91]:
p0, p1

(array([261,  50,  80]), array([241,  59,  78]))

In [92]:
p3 = p0 - p1
p3

array([20, -9,  2])

In [94]:
p = pv.Plotter()
p.add_mesh(pv.PolyData(point_cloud[idx]), color='b')
p.add_lines(np.array([np.array(c), point_cloud[73246]]), color='r')
p.add_lines(np.array([p0, p1 - 3 * p3]), color='g')
p.add_lines(np.array([p0, p1]), color='y')
p.add_mesh(pv.Sphere(22, (169, 60, 105)))
p.show()

/home/simon/anaconda3/envs/shapes/lib/python3.10/site-packages/pyvista/core/utilities/points.py:55: UserWarning: Points is not a float type. This can cause issues when transforming or applying filters. Casting to ``np.float32``. Disable this by passing ``force_float=False``.
  warnings.warn(


Widget(value='<iframe src="http://localhost:44947/index.html?ui=P_0x7c29ac1bd360_33&reconnect=auto" class="pyv…

# Alpha angle

In [7]:
c, r

((169, 60, 105), 22.336863496895106)

In [11]:
inner_sphere = pv.SolidSphere(inner_radius=r, outer_radius=1.2 * r, center=c)
# outer_sphere = pv.SolidSphere(outer_radius=r * 1.2, c)

In [16]:
p = pv.Plotter()
p.add_mesh(pv.PolyData(point_cloud[idx]), color='b')
p.add_mesh(inner_sphere, color='r', opacity=0.5)
p.show()

/home/simon/anaconda3/envs/shapes/lib/python3.10/site-packages/pyvista/core/utilities/points.py:55: UserWarning: Points is not a float type. This can cause issues when transforming or applying filters. Casting to ``np.float32``. Disable this by passing ``force_float=False``.
  warnings.warn(
ERROR:root:bad X server connection. DISPLAY=


: 