In [1]:
import SimpleITK as sitk
import numpy as np
import pyvista as pv
from morphometry.cartilage import knee
from morphometry.image_io import Image

In [2]:
image = Image('nibabel')
image.read_image('/home/simon/Data/Duesseldorf/T1rho/P04/1Relaxed/1Relaxed.nii.gz')

In [3]:
image.transform_coordinate_system()

In [4]:
#p = pv.Plotter()
#p.add_mesh(pv.PolyData(np.argwhere(image.get_array())))
#p.show()

In [5]:
tibia = knee.Tibia(image, 4)

In [6]:
tibia.get_surface_points()

In [7]:
p = pv.Plotter()
p.add_mesh(pv.PolyData(tibia.inferior_surface))
p.add_mesh(pv.PolyData(tibia.superior_surface), color='red')
p.show()

/home/simon/Work/morpohmetry/venv/lib/python3.10/site-packages/pyvista/core/utilities/points.py:55: UserWarning: Points is not a float type. This can cause issues when transforming or applying filters. Casting to ``np.float32``. Disable this by passing ``force_float=False``.
  warnings.warn(


Widget(value='<iframe src="http://localhost:37623/index.html?ui=P_0x72bb6b3fee90_0&reconnect=auto" class="pyvi…

In [8]:
tibia.calculate_landmarks()

In [9]:
tibia.extract_subregions()

[130. 166.]
[-73.  53.] [73. 53.] [-28. -94.] [ 45. -94.]
-
-8346.0 9247.0
---
[131. 165.]
[-73.  53.] [73. 53.] [-29. -93.] [ 44. -93.]
-
-8326.0 9121.0
---
[131. 166.]
[-73.  53.] [73. 53.] [-29. -94.] [ 44. -94.]
-
-8399.0 9194.0
---
[132. 164.]
[-73.  53.] [73. 53.] [-30. -92.] [ 43. -92.]
-
-8306.0 8995.0
---
[132. 165.]
[-73.  53.] [73. 53.] [-30. -93.] [ 43. -93.]
-
-8379.0 9068.0
---
[133. 163.]
[-73.  53.] [73. 53.] [-31. -91.] [ 42. -91.]
-
-8286.0 8869.0
---
[133. 164.]
[-73.  53.] [73. 53.] [-31. -92.] [ 42. -92.]
-
-8359.0 8942.0
---
[133. 165.]
[-73.  53.] [73. 53.] [-31. -93.] [ 42. -93.]
-
-8432.0 9015.0
---
[134. 163.]
[-73.  53.] [73. 53.] [-32. -91.] [ 41. -91.]
-
-8339.0 8816.0
---
[134. 164.]
[-73.  53.] [73. 53.] [-32. -92.] [ 41. -92.]
-
-8412.0 8889.0
---
[134. 165.]
[-73.  53.] [73. 53.] [-32. -93.] [ 41. -93.]
-
-8485.0 8962.0
---
[135. 163.]
[-73.  53.] [73. 53.] [-33. -91.] [ 40. -91.]
-
-8392.0 8763.0
---
[135. 164.]
[-73.  53.] [73. 53.] [-33. -92.] [ 40. 

In [10]:
tibia.left_landmarks

{'center': array([115.27880261, 134.88158621, 171.18038219]),
 'ellipse': 10.0,
 'corners': {'upper_right': array([ 95., 143.]),
  'lower_right': array([175., 143.]),
  'upper_left': array([95., 93.]),
  'lower_left': array([175.,  93.])}}

In [11]:
tibia.right_landmarks

{'center': array([ 47.9453329 , 142.17052872, 164.58877285]),
 'ellipse': 10.0,
 'corners': {'upper_right': array([102.,  72.]),
  'lower_right': array([175.,  72.]),
  'upper_left': array([102.,  19.]),
  'lower_left': array([175.,  19.])}}

In [12]:
p = pv.Plotter()
colors = ['red', 'blue', 'green', 'yellow', 'purple', 'orange', 'cyan', 'magenta', 'grey', 'black']
for i, subregion in enumerate(['clt', 'ilt', 'elt', 'alt', 'plt', 'crt', 'irt', 'ert', 'art', 'prt']):
    if len(getattr(tibia, subregion)) == 0:
        continue
    superior, inferior = knee.get_superior_and_inferior_surface_points(getattr(tibia, subregion), tibia.image.get_transversal_axis(), tibia.image.get_transversal_axis_direction())
    p.add_mesh(pv.PolyData(superior * np.array([1.2, 1, 1])), color=colors[i])
    p.add_mesh(pv.PolyData(inferior), color=colors[i])

p.enable_eye_dome_lighting()
p.show()

Widget(value='<iframe src="http://localhost:36271/index.html?ui=P_0x7b43f6f53940_1&reconnect=auto" class="pyvi…

In [12]:
tibia.calculate_thickness(method='knn')

['x', 'y']
        x    y    z
0      19  130  166
1      19  131  165
2      19  132  164
3      19  133  163
4      19  134  163
...   ...  ...  ...
6143  143  142  174
6144  143  143  174
6145  143  144  174
6146  143  145  174
6147  143  146  174

[6148 rows x 3 columns]
        x    y    z
0      19  130  166
1      19  131  165
2      19  132  164
3      19  133  163
4      19  134  163
...   ...  ...  ...
6143  143  142  174
6144  143  143  174
6145  143  144  174
6146  143  145  174
6147  143  146  174

[6148 rows x 3 columns]
clt
[[106. 132. 169.]
 [106. 132. 170.]
 [106. 132. 171.]
 ...
 [125. 134. 173.]
 [125. 135. 173.]
 [125. 136. 173.]]
['x', 'y']
         x      y      z
0    106.0  132.0  169.0
1    106.0  133.0  169.0
2    106.0  134.0  169.0
3    106.0  135.0  169.0
4    106.0  136.0  169.0
..     ...    ...    ...
303  124.0  138.0  173.0
304  124.0  139.0  173.0
305  125.0  134.0  173.0
306  125.0  135.0  173.0
307  125.0  136.0  173.0

[308 rows x 3 columns]
      

ValueError: Shape of passed values is (0, 1), indices imply (0, 3)

In [10]:
femur = knee.Femur(image, 3)
femur.calculate_thickness(tibia)

{'iclf': {(133.0, 103.0): nan,
  (133.0, 104.0): 1.1372143549025804,
  (133.0, 105.0): 1.8750000000000038,
  (133.0, 106.0): 1.9156678539652912,
  (133.0, 107.0): 1.436750890473945,
  (133.0, 108.0): 1.9156678539652643,
  (133.0, 109.0): 1.9156678539652467,
  (133.0, 110.0): 2.031870773128478,
  (133.0, 111.0): 1.9156678539652467,
  (133.0, 112.0): 2.3945848174565927,
  (133.0, 113.0): 2.354160133097574,
  (133.0, 114.0): 2.356084430483525,
  (133.0, 115.0): 2.6791148380939247,
  (133.0, 116.0): 2.5566817661708288,
  (133.0, 117.0): 3.1249999999999947,
  (134.0, 103.0): 1.2499999999999891,
  (134.0, 104.0): 1.5668386600682245,
  (134.0, 105.0): 1.5668386600682447,
  (134.0, 106.0): 1.9749721045871198,
  (134.0, 107.0): 1.4398341018379166,
  (134.0, 108.0): 2.0259311872983785,
  (134.0, 109.0): 1.9197781385524784,
  (134.0, 110.0): 2.324247610605544,
  (134.0, 111.0): 2.031870773128478,
  (134.0, 112.0): 2.394586669371711,
  (134.0, 113.0): 2.324247610605542,
  (134.0, 114.0): 2.8053587

In [16]:
p = pv.Plotter()
colors = ['red', 'blue', 'green', 'yellow', 'purple', 'orange', 'cyan', 'magenta', 'grey', 'black']
for i, subregion in enumerate(['left_cwbz', 'right_cwbz', 'left_posterior_zone', 'right_posterior_zone', 'left_anterior_zone', 'right_anterior_zone']):
    if len(getattr(femur, subregion)) == 0:
        continue
    if subregion in ['left_posterior_zone', 'right_posterior_zone']:
        tmp = getattr(femur, subregion).copy()
        tmp[:, 1], tmp[:, 0] = tmp[:, 0], tmp[:, 1].copy()  # rotate to allow extraction of anterior and posterior surface
        superior_surface, inferior_surface = knee.get_superior_and_inferior_surface_points(tmp)
        superior_surface[:, 1], superior_surface[:, 0] = superior_surface[:, 0], superior_surface[:, 1].copy()  # rotate back
        inferior_surface[:, 1], inferior_surface[:, 0] = inferior_surface[:, 0], inferior_surface[:, 1].copy()
    else:
        superior_surface, inferior_surface = knee.get_superior_and_inferior_surface_points(getattr(femur, subregion))

    p.add_mesh(pv.PolyData(superior_surface * np.array([1.2, 1, 1])), color=colors[i])
    p.add_mesh(pv.PolyData(inferior_surface), color=colors[i])

p.show()

Widget(value='<iframe src="http://localhost:41585/index.html?ui=P_0x7b9e3d3dddb0_6&reconnect=auto" class="pyvi…

In [18]:
p = pv.Plotter()
tmp = getattr(femur, 'left_posterior_zone').copy()
tmp[:, 1], tmp[:, 0] = tmp[:, 0], tmp[:, 1].copy()
p.add_mesh(pv.PolyData(tmp))
p.enable_eye_dome_lighting()
p.show()

Widget(value='<iframe src="http://localhost:41585/index.html?ui=P_0x7b9e3dee1360_8&reconnect=auto" class="pyvi…

In [19]:
superior_surface, inferior_surface = knee.get_superior_and_inferior_surface_points(tmp)
superior_surface[:, 1], superior_surface[:, 0] = superior_surface[:, 0], superior_surface[:, 1].copy()  # rotate back
inferior_surface[:, 1], inferior_surface[:, 0] = inferior_surface[:, 0], inferior_surface[:, 1].copy()

In [22]:
p = pv.Plotter()
p.add_mesh(pv.PolyData(superior_surface))
p.add_mesh(pv.PolyData(inferior_surface), color='red')
p.enable_eye_dome_lighting()
p.show()

Widget(value='<iframe src="http://localhost:41585/index.html?ui=P_0x7b9e3bbb4d60_11&reconnect=auto" class="pyv…