In [1]:
import SimpleITK as sitk
import numpy as np
import pyvista as pv
from morphometry.cartilage import knee
from morphometry.image_io import Image

In [2]:
image = Image('nibabel')
image.read_image('/home/simon/Data/Duesseldorf/T1rho/P04/1Relaxed/1Relaxed.nii.gz')

In [3]:
image.transform_coordinate_system()

In [4]:
tibia = knee.Tibia(image, 4)

In [5]:
tibia.get_surface_points()

In [6]:
p = pv.Plotter()
p.add_mesh(pv.PolyData(tibia.inferior_surface))
p.add_mesh(pv.PolyData(tibia.superior_surface), color='red')
p.show()

/home/simon/Work/morphometry/venv/lib/python3.10/site-packages/pyvista/core/utilities/points.py:55: UserWarning: Points is not a float type. This can cause issues when transforming or applying filters. Casting to ``np.float32``. Disable this by passing ``force_float=False``.
  warnings.warn(


Widget(value='<iframe src="http://localhost:36707/index.html?ui=P_0x7638c17a4d00_0&reconnect=auto" class="pyvi…

In [7]:
tibia.calculate_landmarks()

In [8]:
tibia.extract_subregions()

In [9]:
tibia.left_landmarks

{'center': array([127.0546671 , 142.17052872, 164.58877285]),
 'ellipse': 10.0,
 'corners': {'upper_right': array([156., 175.]),
  'lower_right': array([156., 102.]),
  'upper_left': array([103., 175.]),
  'lower_left': array([103., 102.])}}

In [10]:
tibia.right_landmarks

{'center': array([ 59.72119739, 134.88158621, 171.18038219]),
 'ellipse': 10.0,
 'corners': {'upper_right': array([ 82., 175.]),
  'lower_right': array([82., 95.]),
  'upper_left': array([ 32., 175.]),
  'lower_left': array([32., 95.])}}

In [11]:
p = pv.Plotter()
colors = ['red', 'blue', 'green', 'yellow', 'purple', 'orange', 'cyan', 'magenta', 'grey', 'black']
for i, subregion in enumerate(['clt', 'ilt', 'elt', 'alt', 'plt', 'crt', 'irt', 'ert', 'art', 'prt']):
    if len(getattr(tibia, subregion)) == 0:
        continue
    superior, inferior = knee.get_superior_and_inferior_surface_points(getattr(tibia, subregion))
    p.add_mesh(pv.PolyData(superior * np.array([1, 1, 1.2])), color=colors[i])
    p.add_mesh(pv.PolyData(inferior), color=colors[i])

p.enable_eye_dome_lighting()
p.show()

Widget(value='<iframe src="http://localhost:36707/index.html?ui=P_0x7638944afee0_1&reconnect=auto" class="pyvi…

In [12]:
tibia.calculate_thickness(method='knn')

clt
[[118. 138. 164.]
 [118. 138. 165.]
 [118. 139. 162.]
 ...
 [137. 142. 165.]
 [137. 143. 164.]
 [137. 143. 165.]]
ilt
[[103. 135. 156.]
 [103. 135. 157.]
 [103. 136. 155.]
 ...
 [124. 132. 167.]
 [124. 132. 168.]
 [124. 133. 168.]]
elt
[[133. 134. 164.]
 [133. 134. 165.]
 [133. 134. 166.]
 ...
 [156. 150. 166.]
 [156. 151. 165.]
 [156. 151. 166.]]
alt
[[113. 113. 169.]
 [113. 113. 170.]
 [113. 114. 168.]
 ...
 [147. 113. 165.]
 [147. 114. 164.]
 [147. 114. 165.]]
plt
[[109. 167. 165.]
 [109. 167. 166.]
 [109. 167. 167.]
 ...
 [145. 161. 166.]
 [145. 162. 165.]
 [145. 162. 166.]]
crt
[[ 50. 134. 173.]
 [ 50. 135. 173.]
 [ 50. 136. 173.]
 ...
 [ 69. 138. 171.]
 [ 69. 138. 172.]
 [ 69. 138. 173.]]
irt
[[ 63. 126. 175.]
 [ 63. 144. 174.]
 [ 64. 124. 172.]
 ...
 [ 82. 127. 162.]
 [ 82. 128. 160.]
 [ 82. 128. 161.]]
ert
[[ 32. 139. 175.]
 [ 32. 140. 175.]
 [ 32. 141. 174.]
 ...
 [ 52. 143. 174.]
 [ 52. 143. 175.]
 [ 53. 129. 176.]]
art
[[ 43. 111. 175.]
 [ 43. 111. 176.]
 [ 43. 112. 174.

{'clt': {(118.0, 138.0): 0.6250000000000004,
  (118.0, 139.0): 1.3975424859373724,
  (118.0, 140.0): 1.7677669529663746,
  (118.0, 141.0): 2.253469547164999,
  (118.0, 142.0): 2.6528335596517523,
  (118.0, 143.0): 2.6516504294495564,
  (118.0, 144.0): 2.253469547164993,
  (118.0, 145.0): 1.9764235376052413,
  (118.0, 146.0): 1.8750000000000038,
  (119.0, 137.0): 1.5329794177400387,
  (119.0, 138.0): 1.3997860176521908,
  (119.0, 139.0): 1.5329794177400344,
  (119.0, 140.0): 1.8766728258315495,
  (119.0, 141.0): 2.3398773248216616,
  (119.0, 142.0): 2.5769410160110446,
  (119.0, 143.0): 2.6528335596517554,
  (119.0, 144.0): 2.3398773248216655,
  (119.0, 145.0): 2.074403744504576,
  (119.0, 146.0): 1.7677669529663629,
  (119.0, 147.0): 1.3975424859373657,
  (119.0, 148.0): 0.6250000000000006,
  (120.0, 136.0): 2.3438970926340437,
  (120.0, 137.0): 2.343897092634042,
  (120.0, 138.0): 2.2590326648497667,
  (120.0, 139.0): 2.343897092634044,
  (120.0, 140.0): 2.5818072315450404,
  (120.0, 

In [13]:
femur = knee.Femur(image, 3)
femur.calculate_thickness(tibia)

{'iclf': {(103.0, 133.0): nan,
  (103.0, 134.0): 1.2499999999999891,
  (103.0, 135.0): nan,
  (103.0, 136.0): nan,
  (103.0, 137.0): nan,
  (103.0, 138.0): 1.2499999999999891,
  (103.0, 139.0): nan,
  (103.0, 140.0): nan,
  (103.0, 141.0): nan,
  (103.0, 142.0): nan,
  (103.0, 143.0): nan,
  (103.0, 144.0): nan,
  (103.0, 145.0): nan,
  (103.0, 146.0): nan,
  (103.0, 147.0): nan,
  (103.0, 148.0): nan,
  (103.0, 149.0): nan,
  (103.0, 150.0): nan,
  (103.0, 151.0): nan,
  (103.0, 152.0): nan,
  (104.0, 133.0): 1.1372143549025804,
  (104.0, 134.0): 1.5668386600682245,
  (104.0, 135.0): 1.8749999999999918,
  (104.0, 136.0): 1.5617020563435877,
  (104.0, 137.0): nan,
  (104.0, 138.0): 1.5668386600682245,
  (104.0, 139.0): 1.874999999999992,
  (104.0, 140.0): nan,
  (104.0, 141.0): nan,
  (104.0, 142.0): nan,
  (104.0, 143.0): nan,
  (104.0, 144.0): nan,
  (104.0, 145.0): nan,
  (104.0, 146.0): nan,
  (104.0, 147.0): nan,
  (104.0, 148.0): nan,
  (104.0, 149.0): nan,
  (104.0, 150.0): nan,

In [23]:
p = pv.Plotter()
colors = ['red', 'blue', 'green', 'yellow', 'purple', 'orange', 'cyan', 'magenta', 'grey', 'black']
for i, subregion in enumerate(['left_cwbz', 'right_cwbz', 'left_posterior_zone', 'right_posterior_zone', 'left_anterior_zone', 'right_anterior_zone']):
    if len(getattr(femur, subregion)) == 0:
        continue
    if subregion in ['left_posterior_zone', 'right_posterior_zone']:
        tmp = getattr(femur, subregion).copy()
        tmp[:, 1], tmp[:, 2] = tmp[:, 2], tmp[:, 1].copy()  # rotate to allow extraction of anterior and posterior surface
        superior_surface, inferior_surface = knee.get_superior_and_inferior_surface_points(tmp)
        superior_surface[:, 1], superior_surface[:, 2] = superior_surface[:, 2], superior_surface[:, 1].copy()  # rotate back
        inferior_surface[:, 1], inferior_surface[:, 2] = inferior_surface[:, 2], inferior_surface[:, 1].copy()
    else:
        superior_surface, inferior_surface = knee.get_superior_and_inferior_surface_points(getattr(femur, subregion))

    p.add_mesh(pv.PolyData(superior_surface * np.array([1, 1, 1.2])), color=colors[i])
    p.add_mesh(pv.PolyData(inferior_surface), color=colors[i])

p.show()

Widget(value='<iframe src="http://localhost:36707/index.html?ui=P_0x76388c1b0130_9&reconnect=auto" class="pyvi…

In [20]:
p = pv.Plotter()
tmp = getattr(femur, 'left_posterior_zone').copy()
tmp[:, 2], tmp[:, 1] = tmp[:, 1], tmp[:, 2].copy()
p.add_mesh(pv.PolyData(tmp))
p.enable_eye_dome_lighting()
p.show()

Widget(value='<iframe src="http://localhost:36707/index.html?ui=P_0x76388c1a4a90_7&reconnect=auto" class="pyvi…

In [21]:
superior_surface, inferior_surface = knee.get_superior_and_inferior_surface_points(tmp)
superior_surface[:, 1], superior_surface[:, 2] = superior_surface[:, 2], superior_surface[:, 1].copy()  # rotate back
inferior_surface[:, 1], inferior_surface[:, 2] = inferior_surface[:, 2], inferior_surface[:, 1].copy()

In [22]:
p = pv.Plotter()
p.add_mesh(pv.PolyData(superior_surface))
p.add_mesh(pv.PolyData(inferior_surface), color='red')
p.enable_eye_dome_lighting()
p.show()

Widget(value='<iframe src="http://localhost:36707/index.html?ui=P_0x76388415a9b0_8&reconnect=auto" class="pyvi…

In [15]:
import SimpleITK as sitk

def register(fixed_image, moving_image):
    translation_transform = sitk.TranslationTransform(fixed_image.GetDimension())
    versor_transform = sitk.VersorRigid3DTransform()
    scale_transform = sitk.ScaleTransform(fixed_image.GetDimension())
    composite_transform = sitk.CompositeTransform(fixed_image.GetDimension())
    # composite_transform.AddTransform(scale_transform)
    # composite_transform.AddTransform(versor_transform)
    composite_transform.AddTransform(translation_transform)

    # Set up the registration method.
    registration_method = sitk.ImageRegistrationMethod()
    registration_method.SetMetricAsMeanSquares()

    registration_method.SetOptimizerAsRegularStepGradientDescent(
        learningRate=0.001,
        minStep=1e-4,
        numberOfIterations=200,
        gradientMagnitudeTolerance=1e-8
    )
    registration_method.SetInitialTransform(composite_transform)
    registration_method.SetInterpolator(sitk.sitkNearestNeighbor)  # Use nearest neighbor to preserve label values.

    # Execute the registration.
    final_transform = registration_method.Execute(fixed_image, moving_image)
    print(registration_method.GetOptimizerStopConditionDescription())
    print(registration_method.GetOptimizerIteration())
    print(registration_method.GetMetricValue())
    print(registration_method.GetMetricNumberOfValidPoints())

    # print("Optimizer's stopping condition:", registration_method.GetStopConditionDescription())

    # Resample the moving image using the final transform.
    registered_moving = sitk.Resample(
        moving_image,
        fixed_image,
        final_transform,
        sitk.sitkNearestNeighbor,  # ensures labels aren’t smoothed by interpolation
        0.0,
        moving_image.GetPixelIDValue()
    )

    return registered_moving

In [16]:

import numpy as np
from pathlib import Path
from tqdm import tqdm

for patient in Path('/home/simon/Data/Duesseldorf/T1rho/').iterdir():
    if not patient.is_dir():
        continue

    relaxed_image = sitk.ReadImage(f'/home/simon/Data/Duesseldorf/T1rho/{patient.name}/1Relaxed/1Relaxed.nii.gz')
    med_to_lat_image = sitk.ReadImage(f'/home/simon/Data/Duesseldorf/T1rho/{patient.name}/2MedToLat/2MedToLat.nii.gz')
    lat_to_med_image = sitk.ReadImage(f'/home/simon/Data/Duesseldorf/T1rho/{patient.name}/3LatToMed/3LatToMed.nii.gz')

    relaxed_image = sitk.Cast(relaxed_image, sitk.sitkFloat32)
    lat_to_med_image = sitk.Cast(lat_to_med_image, sitk.sitkFloat32)
    med_to_lat_image = sitk.Cast(med_to_lat_image, sitk.sitkFloat32)

    print(patient.name)
    registered_lat_to_med = register(relaxed_image, lat_to_med_image)
    print('lat_to_med')
    # registered_med_to_lat = register(relaxed_image, med_to_lat_image)
    print('med_to_lat')

    sitk.WriteImage(registered_med_to_lat, f'/home/simon/Data/Duesseldorf/T1rho/{patient.name}/2MedToLat/2MedToLat_registered.nii.gz')
    sitk.WriteImage(registered_lat_to_med, f'/home/simon/Data/Duesseldorf/T1rho/{patient.name}/3LatToMed/3LatToMed_registered.nii.gz')

P15
RegularStepGradientDescentOptimizerv4: Maximum number of iterations (200) exceeded.
200
0.4796077355055941
2379211
lat_to_med
med_to_lat
P10


MeanSquaresImageToImageMetricv4 (0x69ecf80): No valid points were found during metric evaluation. For image metrics, verify that the images overlap appropriately. For instance, you can align the image centers by translation. For point-set metrics, verify that the fixed points, once transformed into the virtual domain space, actually lie within the virtual domain.



RegularStepGradientDescentOptimizerv4: Gradient magnitude tolerance met after 0 iterations. Gradient magnitude (0) is less than gradient magnitude tolerance (1e-08).
1
1.7976931348623157e+308
0
lat_to_med
med_to_lat
P12


MeanSquaresImageToImageMetricv4 (0x6d29f20): No valid points were found during metric evaluation. For image metrics, verify that the images overlap appropriately. For instance, you can align the image centers by translation. For point-set metrics, verify that the fixed points, once transformed into the virtual domain space, actually lie within the virtual domain.



RegularStepGradientDescentOptimizerv4: Gradient magnitude tolerance met after 0 iterations. Gradient magnitude (0) is less than gradient magnitude tolerance (1e-08).
1
1.7976931348623157e+308
0
lat_to_med
med_to_lat
P13
RegularStepGradientDescentOptimizerv4: Gradient magnitude tolerance met after 0 iterations. Gradient magnitude (0) is less than gradient magnitude tolerance (1e-08).
1
0.0
5
lat_to_med
med_to_lat
P08
RegularStepGradientDescentOptimizerv4: Gradient magnitude tolerance met after 0 iterations. Gradient magnitude (0) is less than gradient magnitude tolerance (1e-08).
1
0.0
112023
lat_to_med
med_to_lat
P05
RegularStepGradientDescentOptimizerv4: Maximum number of iterations (200) exceeded.
200
0.05362868490238854
893850
lat_to_med
med_to_lat
P06
RegularStepGradientDescentOptimizerv4: Maximum number of iterations (200) exceeded.
200
0.02648362041710326
1489751
lat_to_med
med_to_lat
P16
RegularStepGradientDescentOptimizerv4: Maximum number of iterations (200) exceeded.
200
0.01

In [10]:
relaxed_image = sitk.ReadImage(f'/home/simon/Data/Duesseldorf/T1rho/P04/1Relaxed/1Relaxed.nii.gz')
moi = sitk.ReadImage('/home/simon/Data/Duesseldorf/T1rho/P04/3LatToMed/3LatToMed.nii.gz')
moi = sitk.ReadImage('/home/simon/Data/Duesseldorf/T1rho/P04/2MedToLat/2MedToLat.nii.gz')
relaxed_image = sitk.Cast(relaxed_image, sitk.sitkFloat32)
moi = sitk.Cast(moi, sitk.sitkFloat32)
register(relaxed_image, moi)


RegularStepGradientDescentOptimizerv4: Step too small after 40 iterations. Current step (6.10352e-05) is less than minimum step (0.0001).
41
0.13701692880685695
9037022


<SimpleITK.SimpleITK.Image; proxy of <Swig Object of type 'itk::simple::Image *' at 0x7fcf6c1cf660> >